config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
      @heaiding = 'Страничка про нас!'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to posts_path
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))
      redirect_to @post
    else
      render 'new'
    end
  end

  def create
    # render plain: params[:post].inspect

    @post = Post.new(post_params)

    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
          <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
            <h4>MyBlog</h4>
          </a>
  <!-- <span><%= link_to "MyBlog", home_path, :class => 'd-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none'%></span> -->

          <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><span><%= link_to "Home", home_path, :class => 'nav-link px-2 link-secondary'%></span></li>
            <li><span><%= link_to "About", about_path, :class => 'nav-link px-2 link-dark'%></span></li>
            <li><span><%= link_to "New post", new_post_path, :class => 'nav-link px-2 link-dark'%></span></li>
          </ul>

          <%# <div class="col-md-3 text-end">
            <button type="button" class="btn btn-outline-primary me-2">Login</button>
            <button type="button" class="btn btn-primary">Sign-up</button>
          </div> %>
        </header>
      </div>

  <div class="container"
    <br>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h3><%= @heaiding %><h3>
  <p>быр быр быр</p>

app/views/posts/edit.html.erb
<h2>Редактирование поста</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Название<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    Название статьи<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1>Все наши посты</h1>
<br><br>

<% @post.each do |post|%>
  <div class="alert alert-light">
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to "Читать далее", post_path(post), :class => 'btn btn-outline-primary' %>
    <hr>
  </div>
<% end %>

app/views/posts/new.html.erb
<h2>Добавление нового поста</h2>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Название<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    Название статьи<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<br><br>
<p><%= @post.body %></p>
<hr>
<%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Удалить пост", post_path(@post), method: :delete, data:{confirm: "Хотите удалить статью?"}  ,:class => 'btn btn-danger' %>
<hr>
<h2>Все комментарии</h2>
<br>
<% @post.comments.each do |comment|%>
  <div class="alert alert-light">
    <p><strong><%= comment.username %></strong>: <%= comment.body %></p>
  </div>
<% end %>

<hr>
<h2>Добавление комментария</h2>
<%= form_for([@post, @post.comments.build])  do |f| %>
  <p>
    Пользователь<br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>
  <p>
    Комментарий<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit("Доавить комментарий", {:class => 'btn btn-success'}) %>
  </p>
<% end %>